// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels(in *jlexer.Lexer, out *Rss) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels(out *jwriter.Writer, in Rss) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Rss) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Rss) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Rss) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Rss) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels(l, v)
}
func easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels1(in *jlexer.Lexer, out *News) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "pubDate":
			out.PubDate = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels1(out *jwriter.Writer, in News) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"pubDate\":"
		out.RawString(prefix)
		out.String(string(in.PubDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v News) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v News) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4bfd1b6eEncodeGithubComgeoirbTochkaTestPkgModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *News) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *News) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4bfd1b6eDecodeGithubComgeoirbTochkaTestPkgModels1(l, v)
}
